# Generated by Django 5.0.3 on 2024-08-16 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answeredquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='userquizprogress',
            name='current_question',
        ),
        migrations.AddField(
            model_name='userquizprogress',
            name='last_answered_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_answered_progress', to='quiz.question'),
        ),
    ]
