# Generated by Django 5.0.3 on 2024-08-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeredquestion',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.answer'),
        ),
    ]
